export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const FILTER_PRODUCT_BY_PRICE = "FILTER_PRODUCT_BY_PRICE";
export const FILTER_PRODUCTS_BY_QUANTITY = "FILTER_PRODUCTS_BY_QUANTITY";